language: java
jdk: openjdk8
dist: trusty
sudo: false

branches:
  only: master

jobs:
  include:
    - stage: test
      name: "Run Tests"
      script: ./gradlew --stacktrace check
    - stage: deploy
      name: "Upload Snapshot"
      script: ./script/upload_snapshot.sh

stages:
  - test
  - name: deploy
    if: branch = master AND type != pull_request
